name: Build

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Prepare
        run: make prepare

      - name: Build
        run: |
          make build-web
          make package os=darwin arch=amd64
          make package os=darwin arch=arm64
          make package os=linux arch=amd64
          make package os=linux arch=arm64
          make package os=windows arch=amd64

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: build/*
