name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 16.14.2

    - name: Prepare
      run: make prepare

    - name: Lint Web
      run: cd web && npm run lint

    # TODO: Fix Go lint action
    # - name: Lint Server
    #   uses: golangci/golangci-lint-action@v2
    #   with: 
    #     version: v1.45
