name: Lint

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2

      - name: Prepare
        run: make prepare

      - name: Lint Web
        run: cd web && npm run lint

